using Moq;
using TalesOfTribute;
using TalesOfTribute.AI;
using TalesOfTribute.Board;
using TalesOfTribute.Serializers;

namespace Tests.AI;

public class RandomBotTests
{
    public BoardManager _boardManager = new BoardManager(new[] { PatronId.PELIN, PatronId.TREASURY });
    private RandomBot r1 = new RandomBot();
    private RandomBot r2 = new RandomBot();

    [Fact]
    public void SimplePlayTest()
    {
        
        _boardManager.SetUpGame();
        TalesOfTributeApi api = new TalesOfTributeApi(_boardManager);

        var sut = new TalesOfTributeGame(new []{ r1, r2}, api);
        var result = sut.Play();
        Console.WriteLine(result.Winner);
        Console.WriteLine(result.Reason);
        Console.WriteLine(result.AdditionalContext);
    }
}
/*
class AutoGeneratedProgram {static void Main(string[] args){
    RandomBotTests x = new RandomBotTests();
    x.SimplePlayTest();
}}
*/